### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by Sh3Rm4n** [stm32-rs/stm32f3xx-hal#177]
- [x] Merge #173 
- [x] Merge #172
- [x] Test all examples
  - [x] adc (_only smoke test _) [1]
  - [x] can (_only smoke test_) [1]
  - [x] gpio_erased
  - [x] i2c_scanner
  - [x] pwm (_only smoke test_) [1]
  - [x] serial_dma
  - [x] spi
  - [x] toggle
  - [x] usb_serial
- [x] Run all tests
  - [x] Rcc
- [x] Update Changelog
  - [x] Top Version
  - [x] Bottom Version Link
- [x] No Dead Links
- [x] Bump Cargo.toml
- [x] Update references to version (Documentation Links)
- [ ] Tag and Relase on Github
- [ ] Release on crates.io

[1]: Did not panic!
